version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./chat_history.db:/app/backend/chat_history.db
      - ./.env:/app/.env
      - ./ragbase:/app/ragbase
      - ./config:/app/config
      - ./images:/app/images

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./.env:/app/.env
      - ./ragbase:/app/ragbase
      - ./config:/app/config
      - ./images:/app/images

volumes:
  qdrant_data:
